Deje.Web.Admin/Controllers/ArtikliController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Deje.Core.Model;
using Deje.Core.Repository;
using Deje.Core.Status;
using Deje.Web.Admin.Services;
using DevExpress.Web.Mvc;

namespace Deje.Web.Admin.Controllers
{
    public class ArtikliController : Controller
    {

        private readonly IArtikliRepository m_ArtikliRepository;

        private readonly IKategorijeArtikalaRepository m_KategorijeArtikalaRepository;

        private IDobavljaciRepository m_DobavljaciRepository;

        public ArtikliController(IArtikliRepository artikliRepository, IKategorijeArtikalaRepository kategorijeArtikalaRepository, 
            IDobavljaciRepository dobavljaciRepository)
        {
            m_ArtikliRepository = artikliRepository;
            m_KategorijeArtikalaRepository = kategorijeArtikalaRepository;
            m_DobavljaciRepository = dobavljaciRepository;
        } 

        public ActionResult Index(int? idDobavljaca)
        {
            IEnumerable<Artikal> artikli = Enumerable.Empty<Artikal>();
            if (idDobavljaca.HasValue)
            {
                ViewBag.KategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
                artikli = VratiArtikleDobavljaca(idDobavljaca.Value);
                ViewBag.IdDobavljaca = idDobavljaca.Value;
            }
            return View(artikli);
        }

        public PartialViewResult VratiArtikleCallback(int idDobavljaca)
        {
            var kategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
            var artikli = VratiArtikleDobavljaca(idDobavljaca);
            ViewBag.KategorijeArtikala = kategorijeArtikala;
            ViewBag.IdDobavljaca = idDobavljaca;
            return PartialView("ArtikliGrid", artikli);
        }

        public ActionResult Kreiraj(int idDobavljaca)
        {
            ViewBag.KategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
            var dobavljac = m_DobavljaciRepository.VratiPoId(idDobavljaca);
            TempData["Status"] = new StatusKreirajNovi();
            return View("Artikal", new Artikal{IdDobavljaca = idDobavljaca, Aktivan = true, Dobavljac = dobavljac});
        }

        public ActionResult Modifikuj(int id)
        {
            ViewBag.KategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
            var artikal = m_ArtikliRepository.VratiArtikal(id, x => x.Dobavljac);
            return View("Artikal", artikal);
        }

        public ActionResult SacuvajArtikal(Artikal artikal, string nazivDobavljaca)
        {
            ViewBag.KategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
            if (!ModelState.IsValid)
            {
                TempData["Status"] = new StatusValidationError();
                artikal.Dobavljac = new Dobavljac {Naziv = nazivDobavljaca};
                return View("Artikal", artikal);
            }
            var slika = UploadControlExtension.GetUploadedFiles("slikaUploadControl").SingleOrDefault();
            if (slika != null && slika.ContentLength > 0)
            {
                var url = ((BlobStorage) HttpContext.Application["storage"]).SacuvajSlikuArtikla(slika.FileContent, 
                    slika.ContentType, Path.GetExtension(slika.FileName));
                artikal.Slika = url;
            }
            m_ArtikliRepository.Sacuvaj(artikal);
            TempData["Status"] = new StatusSaved();
            return RedirectToAction("Modifikuj", new {artikal.Id});
        }

        private IEnumerable<Artikal> VratiArtikleDobavljaca(int idDobavljaca)
        {
            var artikli = m_ArtikliRepository.VratiArtikleDobaljvaca(idDobavljaca);
            return artikli;
        }



        public PartialViewResult VratiArtiklePretrageCallback(int idDobavljaca)
        {
            ViewBag.IdDobavljaca = idDobavljaca;
            ViewBag.KategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
            var artikli = m_ArtikliRepository.VratiSveArtikle();
            return PartialView("PretragaArtikalaGrid", artikli);
        }

        public ActionResult KopirajArtikal(int idArtikla, int idDobavljaca)
        {
            ViewBag.KategorijeArtikala = m_KategorijeArtikalaRepository.VratiSve();
            var artikal = m_ArtikliRepository.VratiArtikal(idArtikla, x => x.Dobavljac);
            artikal.Id = 0;
            artikal.IdDobavljaca = idDobavljaca;
            return View("Artikal", artikal);
        }
    }
}

Deje.Web.Admin/Controllers/DobavljaciController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Deje.Core.Manager;
using Deje.Core.Model;
using Deje.Core.Repository;
using Deje.Core.Status;
using Deje.Web.Admin.Model;
using Deje.Web.Admin.Services;
using DevExpress.Web.ASPxUploadControl;
using DevExpress.Web.Mvc;

namespace Deje.Web.Admin.Controllers
{
    public class DobavljaciController : Controller
    {
        private readonly IDobavljaciRepository m_DobavljaciRepository;

        private readonly IDelatnostiRepository m_DelatnostiRepository;

        private readonly DobavljaciManager m_DobavljaciManager;

        private readonly IVrsteDobavljacaRepository m_VrsteDobavljacaRepository;

        private readonly IStatusiRepository m_StatusiRepository;

        public DobavljaciController(IDobavljaciRepository dobavljaciRepository, IDelatnostiRepository delatnostiRepository, DobavljaciManager dobavljaciManager,
            IVrsteDobavljacaRepository vrsteDobavljacaRepository, IStatusiRepository statusiRepository)
        {
            m_DobavljaciRepository = dobavljaciRepository;
            m_DelatnostiRepository = delatnostiRepository;
            m_DobavljaciManager = dobavljaciManager;
            m_VrsteDobavljacaRepository = vrsteDobavljacaRepository;
            m_StatusiRepository = statusiRepository;
        }

        public ActionResult Index()
        {
            var dobavljaci = m_DobavljaciRepository.VratiSve();
            return View(dobavljaci);
        }

        public PartialViewResult VratiDobavljacePartial()
        {
            var dobavljaci = m_DobavljaciRepository.VratiSve();
            return PartialView("DobavljaciGrid", dobavljaci);
        }

        public ActionResult KreirajNovog()
        {
            var dobavljac = new Dobavljac{GpsLatitude = 45.25, GpsLongitude = 19.85, Kontakt = new Kontakt()};
            ViewData["Delatnosti"] = m_DelatnostiRepository.VratiSve();
            ViewBag.StatusiDobavljaca = m_StatusiRepository.VratiStatuseDobavljaca();
            TempData["Status"] = new StatusKreirajNovi();
            return View("PregledDobavljaca", dobavljac);
        }

        public ActionResult Sacuvaj(Dobavljac dobavljac)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Delatnosti"] = m_DelatnostiRepository.VratiSve();
                if (dobavljac.IdDelatnosti.HasValue)
                {
                    var vrsteDobavljaca = m_VrsteDobavljacaRepository.VratiZaDelatnost(dobavljac.IdDelatnosti.Value);
                    ViewBag.VrsteDobavljaca = vrsteDobavljaca;
                }
                ViewBag.StatusiDobavljaca = m_StatusiRepository.VratiStatuseDobavljaca();
                TempData["Status"] = new StatusValidationError();
                return View("PregledDobavljaca", dobavljac);
            }
            
            var slike = UploadControlExtension.GetUploadedFiles("slikaDobavljacaUpload");
            var slika = slike.SingleOrDefault();
            if (slika != null && slika.ContentLength > 0)
            {
                var putanja = ((BlobStorage) HttpContext.Application["storage"]).SacuvajSlikuDobavljaca(slika.FileContent,
                                                                                          slika.ContentType,
                                                                                          Path.GetExtension(slika.FileName));
                dobavljac.Slika = putanja;
            }
            var id = m_DobavljaciRepository.Save(dobavljac);
            TempData["Status"] = new StatusSaved();
            return RedirectToAction("Izmeni", new {id});
        }

        public ActionResult Izmeni(int id)
        {
            var dobavljac = m_DobavljaciRepository.VratiPoId(id);
            ViewData["Delatnosti"] = m_DelatnostiRepository.VratiSve();
            var vrsteDobavljaca = m_VrsteDobavljacaRepository.VratiZaDelatnost(dobavljac.IdDelatnosti.Value);
            ViewBag.VrsteDobavljaca = vrsteDobavljaca;
            ViewBag.StatusiDobavljaca = m_StatusiRepository.VratiStatuseDobavljaca();
            return View("PregledDobavljaca", dobavljac);
        }

        public ActionResult Obrisi(int id)
        {
            m_DobavljaciRepository.Delete(id);
            return RedirectToAction("Index");
        }

        public PartialViewResult VratiRezultatePretrageCallback(string rezultati)
        {
            var jss = new JavaScriptSerializer();
            var rez = jss.Deserialize<RezultatPretrage[]>(rezultati);
            return PartialView("PretragaAdresaGrid", rez);
        }

        public PartialViewResult VratiVrsteDobavljacaCallback(int idDelatnosti)
        {
            var vrsteDobavljaca = m_VrsteDobavljacaRepository.VratiZaDelatnost(idDelatnosti);
            ViewBag.VrsteDobavljaca = vrsteDobavljaca;
            return PartialView("VrsteDobavljacaCombo");
        }

        [HttpPost]
        public void SacuvajLokaciju(int id, double latitude, double longitude, int zoom)
        {
            m_DobavljaciManager.SacuvajLokacijuDobavljaca(id,latitude, longitude, zoom);
        }

        public ActionResult Pretraga()
        {
            return View();
        }

        public JsonResult Pretrazi(double latitude, double longitude, double distance)
        {
            var rezultati = m_DobavljaciRepository.VratiDobavljaceUOkolini(latitude, longitude, distance);
            return Json(rezultati, JsonRequestBehavior.AllowGet);
        }

        public ActionResult VratiGalerijuSlika(int id)
        {
            var slike = m_DobavljaciRepository.VratiSlikeDobavljaca(id).Select(x => new {image = @Url.Content("~/Slike/" + x.SlikaSaEkstenzijom)}).ToArray();
            return Json(slike, JsonRequestBehavior.AllowGet);
        }

        public void DodajUGaleriju(int id)
        {
            var files = UploadControlExtension.GetUploadedFiles("upload");
            foreach (var uploadedFile in files)
            {
                SacuvajSlikuUGaleriju(id, uploadedFile);
            }
        }

        private void SacuvajSlikuUGaleriju(int idDobavljaca, UploadedFile slika)
        {
            var slikaDobavljaca = new SlikeDobavljaca { Id = Guid.NewGuid(), IdDobavljaca = idDobavljaca, Ekstenzija = ".jpg" };
            m_DobavljaciRepository.DodajSliku(slikaDobavljaca);
        }

        public void ObrisiSliku(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var fullPath = Server.MapPath(id);
                try
                {
                    System.IO.File.Delete(fullPath);
                }
                catch
                {
                }
                var lastSlash = id.LastIndexOf("/");
                var image = id.Substring(lastSlash);
                var imageId = Path.GetFileNameWithoutExtension(image);
                m_DobavljaciRepository.ObrisiSliku(Guid.Parse(imageId));
            }
            
        }

        public PartialViewResult VratiDobavljaceComboBoxCallback(int width, int? idDobavljaca)
        {
            var dobavljaci = m_DobavljaciRepository.VratiSve();
            ViewBag.Dobavljaci = dobavljaci;
            ViewBag.ComboWidth = width;
            return PartialView("DobavljaciComboBox", idDobavljaca);
        }
    }
}

Deje.Web.Admin/Views/Artikli/Artikal.cshtml
@using System.Web.UI.WebControls
@using Deje.Core.Model
@model Deje.Core.Model.Artikal

@{
    ViewBag.Title = Model.Id == 0 ? "Novi artikal" : Model.Naziv;
}
<script>
    function kopirajArtikalClick(s, e) {
        gvPretragaArtikala.PerformCallback();
    }

    function gvPretragaArtikalaBeginCallback(s, e) {
        e.customArgs['idDobavljaca'] = $("#IdDobavljaca").val();
    }
</script>


@using (Html.BeginForm("SacuvajArtikal", "Artikli", FormMethod.Post, new { @class = "edit_form" }))
{
    <div style="float: left; width: 200px;">
        <div class="line">
        @Html.DevExpress().HyperLink(x =>
        {
            x.Name = "lnknNazad";
            x.Properties.Text = "Nazad";
            x.NavigateUrl = @Url.Action("Index", "Artikli", new {Model.IdDobavljaca});
        }).GetHtml()
        @Html.HiddenFor(x => x.Slika)

        @Html.DevExpress().Image(x =>
                                     {
                                         x.Name = "Slika";
                                         x.Width = Unit.Pixel(200);
                                         x.Height = Unit.Pixel(210);
                                     }).Bind(Model.Slika).GetHtml()
        @Html.DevExpress().UploadControl(x =>
                                             {
                                                 x.Name = "slikaUploadControl";
                                                 x.ValidationSettings.AllowedFileExtensions = new[]{".jpg", ".png"};
                                                 x.Width = Unit.Pixel(200);
                                             }).GetHtml()
    </div>
    </div>

    <div style="float: left; margin: 0 0 0 10px;">
        
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.IdDobavljaca)
        <div class="line" style="margin-bottom: 18px;">
            @Html.DevExpress().HyperLink(x =>
                                             {
                                                 x.Name = "lnkKopiraj";
                                                 x.Properties.Text = "Kopiraj";
                                                 x.Properties.ClientSideEvents.Click = "kopirajArtikalClick";
                                                 x.ControlStyle.Cursor = "pointer";
                                             }).GetHtml()
        </div>
        <div class="line">
            @Html.DevExpress().Label(x =>
                                         {
                                             x.Text = "Dobavljač: ";
                                             x.AssociatedControlName = "NazivDobavljaca";
                                             x.ControlStyle.CssClass = "label";
                                         }).GetHtml()
            @Html.DevExpress().TextBox(textEdit => 
                                           {
                                               textEdit.Name = "NazivDobavljaca";
                                               textEdit.ControlStyle.CssClass = "editor";
                                               textEdit.ReadOnly = true;
                                           }).Bind(Model.Dobavljac.Naziv).GetHtml()
        </div>
        <div class="line">
            @Html.DevExpress().Label(label =>
                                         {
                                             label.Text = "Kategorija artikla: ";
                                             label.ControlStyle.CssClass = "label";
                                             label.AssociatedControlName = "IdKategorijeArtikle";
                                         }).GetHtml()
      
            @Html.DevExpress().ComboBox(s =>
                                            {
                                                s.Name = "IdKategorijeArtikla";
                                                s.ShowModelErrors = true;
                                                s.Properties.DropDownRows = 30;
                                                s.Properties.ValueType = typeof(int);
                                                s.Properties.ValueField = "Id";
                                                s.Properties.TextField = "Naziv";
                                                s.ControlStyle.CssClass = "editor";
                                            }).BindList(ViewBag.KategorijeArtikala).Bind(Model.IdKategorijeArtikla).GetHtml()
        </div>
        <div class="line">
            @Html.DevExpress().Label(label =>
                                         {
                                             label.Text = "Naziv artikla: ";
                                             label.ControlStyle.CssClass = "label";
                                             label.AssociatedControlName = "Naziv";
                                         }).GetHtml()
      
            @Html.DevExpress().TextBox(textEdit => 
                                           {
                                               textEdit.Name = "Naziv";
                                               textEdit.Properties.ConvertEmptyStringToNull = true;
                                               textEdit.ShowModelErrors = true;
                                               textEdit.ControlStyle.CssClass = "editor";
                                           }).Bind(Model.Naziv).GetHtml()
        </div>
        <div class="line">
        
            @Html.DevExpress().Label(label =>
                                         {
                                             label.Text = "Cena: ";
                                             label.ControlStyle.CssClass = "label";
                                             label.AssociatedControlName = "Cena";
                                         }).GetHtml()
            @Html.DevExpress().SpinEdit(x =>
                                            {
                                                x.Name = "Cena";
                                                x.ShowModelErrors = true;
                                                x.Properties.MinValue = 0;
                                                x.Properties.NumberType = SpinEditNumberType.Float;
                                                x.Properties.NumberFormat = SpinEditNumberFormat.Number;
                                                x.Properties.DecimalPlaces = 2;
                                                x.Properties.SpinButtons.ShowIncrementButtons = false;
                                                x.Properties.DisplayFormatString = "n2";
                                                x.ControlStyle.CssClass = "editor";
                                                x.Properties.AllowMouseWheel = false;
                                                x.ControlStyle.HorizontalAlign = HorizontalAlign.Right;
                                            }).Bind(Model.Cena).GetHtml()
        </div>
        <div class="line">
            @Html.DevExpress().Label(label =>
                                         {
                                             label.Text = "Opis: ";
                                             label.ControlStyle.CssClass = "label";
                                             label.AssociatedControlName = "Opis";
                                         }).GetHtml()
            <div style="clear: left; width: 394px;">
                @Html.DevExpress().Memo(x =>
                                        {
                                            x.Name = "Opis";
                                            //x.ControlStyle.CssClass = "editor";
                                            x.ShowModelErrors = true;
                                            x.Width = Unit.Percentage(100);
                                            x.Height = Unit.Pixel(100);
                                        }).Bind(Model.Opis).GetHtml()
            </div>
            
        </div>
        
        <div class="line">
            @Html.DevExpress().Label(label =>
                                         {
                                             label.Text = "Aktivan: ";
                                             label.ControlStyle.CssClass = "label";
                                             label.AssociatedControlName = "Aktivan";
                                         }).GetHtml()
            @Html.DevExpress().CheckBox(x =>
                                            {
                                                x.Name = "Aktivan";
                                                x.ControlStyle.CssClass = "editor";
                                            }).Bind(Model.Aktivan).GetHtml()
        </div>
        <div class="line">
            
            @Html.DevExpress().Button(x =>
                                          {
                                              x.Name = "btnSacuvaj";
                                              x.Text = "Sačuvaj";
                                              x.UseSubmitBehavior = true;
                                              //x.Style.Add("float", "right");
                                              //x.Style.Add("margin-right", "128px");
                                          }).GetHtml()
        </div>
    </div>
}

@Html.DevExpress().PopupControl(x =>
{
    x.Name = "pretragaArtikalaPopup";
    x.Modal = true;
    x.PopupVerticalAlign = PopupVerticalAlign.Above;
    x.PopupHorizontalAlign = PopupHorizontalAlign.OutsideRight;
    x.HeaderText = "Izbor artikla";
    x.PopupElementID = "lnkKopiraj";
    x.SetContent(() =>
                     {
                         @Html.RenderPartial("PretragaArtikalaGrid", Enumerable.Empty<Artikal>());
                     });
    x.Width = Unit.Pixel(600);
}).GetHtml()

Deje.Web.Admin/Views/Artikli/ArtikliGrid.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Deje.Core.Model.Artikal>


@Html.DevExpress().GridView(s =>
{
    s.Name = "gvArtikli";
    s.Caption = "Artikli";
    s.CallbackRouteValues = new {Controller = "Artikli", Action = "VratiArtikleCallback"};
    
    s.Columns.Add(c =>
    {
        c.SetHeaderTemplateContent(tc =>
        {
            @Html.DevExpress().HyperLink(ls =>
            {
                ls.Name = "lnkNew";
                ls.Properties.Text = "Dodaj nov";
                ls.NavigateUrl = @Url.Action("Kreiraj", new { ViewBag.IdDobavljaca });
                ls.ControlStyle.Cursor = "pointer";
            }).Render();
        });
        c.SetDataItemTemplateContent(tc =>
        {
            var id = DataBinder.Eval(tc.DataItem, "Id");
            @Html.DevExpress().HyperLink(ls =>
            {
                ls.Name = "lnkModifikuj_" + id;
                ls.Properties.Text = "Edit";
                ls.NavigateUrl = @Url.Action("Modifikuj", new { id});
                ls.ControlStyle.Cursor = "pointer";
            }).Render();
        });
    });
    s.Columns.Add(c =>
    {
        c.FieldName = "IdKategorijeArtikla";
        c.Caption = "Kategorija";
        c.ColumnType = MVCxGridViewColumnType.ComboBox;
        var editor = (ComboBoxProperties)c.PropertiesEdit;
        editor.TextField = "Naziv";
        editor.ValueType = typeof(int);
        editor.ValueField = "Id";
        editor.DataSource = ViewBag.KategorijeArtikala;
        c.GroupIndex = 0;
    });
    s.Columns.Add(c =>
                      {
                          //c.FieldName = "LinkSlike";
                          //c.Caption = "Slika";
                          c.SetDataItemTemplateContent(tc =>
                                                           {
                                                               @Html.DevExpress().Image(i =>
                                                                                            {
                                                                                                i.ImageUrl = (string) DataBinder.Eval(tc.DataItem, "Slika");
                                                                                                i.Height = Unit.Pixel(50);
                                                                                                i.Width = Unit.Pixel(50);
                                                                                            }).Render();
                                                           });
                      });
    s.Columns.Add("Naziv", "Naziv artikla");
    s.Columns.Add("Cena").PropertiesEdit.DisplayFormatString = "n2";
    s.Columns.Add(c =>
                      {
                          c.FieldName = "Aktivan";
                          c.ColumnType = MVCxGridViewColumnType.CheckBox;
                      });
    s.SettingsPager.PageSize = 8;
    s.Width = Unit.Percentage(100);
    s.KeyFieldName = "Id";
    s.ClientSideEvents.BeginCallback = "gvArtikliBeginCallback";
    s.Settings.ShowColumnHeaders = true;
}).Bind(Model).GetHtml()
      

Deje.Web.Admin/Views/Artikli/Index.cshtml
@model IEnumerable<Deje.Core.Model.Artikal>

@{
    ViewBag.Title = "Artikli";
}

<script>

    function IdDobavljacaValueChanged(s, e) {
        if (!gvArtikli.InCallback()) {
            gvArtikli.PerformCallback();
        }
    }
    
    function gvArtikliBeginCallback(s, e) {
        e.customArgs['idDobavljaca'] = IdDobavljaca.GetValue();
    }
</script>

<div class="line">
    @Html.DevExpress().Label(x =>
                                 {
                                     x.ControlStyle.CssClass = "label";
                                     x.AssociatedControlName = "IdDobavljaca";
                                     x.Text = "Dobavljač: ";
                                 }).GetHtml()
    @Html.Action("VratiDobavljaceComboBoxCallback", "Dobavljaci", new{width = 216, ViewBag.IdDobavljaca})    
</div>

<div class="line" style="width: 400px; margin-top: 10px;">
    @Html.Partial("ArtikliGrid", Model)
</div>

Deje.Web.Admin/Views/Artikli/PretragaArtikalaGrid.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Deje.Core.Model.Artikal>


@Html.DevExpress().GridView(s =>
{
    s.Name = "gvPretragaArtikala";
    s.Caption = "Artikli";
    s.CallbackRouteValues = new {Controller = "Artikli", Action = "VratiArtiklePretrageCallback"};
    
    s.Columns.Add(c =>
    {
        c.SetDataItemTemplateContent(tc =>
        {
            var id = DataBinder.Eval(tc.DataItem, "Id");
            @Html.DevExpress().HyperLink(ls =>
            {
                ls.Name = "lnkIzaberi_" + id;
                ls.Properties.Text = "Izaberi";
                ls.NavigateUrl = @Url.Action("KopirajArtikal", "Artikli", new { idArtikla = id, idDobavljaca = ViewBag.IdDobavljaca});
                ls.ControlStyle.Cursor = "pointer";
            }).Render();
        });
    });
    s.Columns.Add(c =>
    {
        c.FieldName = "IdKategorijeArtikla";
        c.Caption = "Kategorija";
        c.ColumnType = MVCxGridViewColumnType.ComboBox;
        var editor = (ComboBoxProperties)c.PropertiesEdit;
        editor.TextField = "Naziv";
        editor.ValueType = typeof(int);
        editor.ValueField = "Id";
        editor.DataSource = ViewBag.KategorijeArtikala;
        //c.GroupIndex = 0;
    });
    s.Columns.Add(c =>
                      {
                          //c.FieldName = "LinkSlike";
                          //c.Caption = "Slika";
                          c.SetDataItemTemplateContent(tc =>
                                                           {
                                                               @Html.DevExpress().Image(i =>
                                                                                            {
                                                                                                i.ImageUrl = (string) DataBinder.Eval(tc.DataItem, "LinkSlike");
                                                                                                i.Height = Unit.Pixel(50);
                                                                                                i.Width = Unit.Pixel(50);
                                                                                            }).Render();
                                                           });
                      });
    s.Columns.Add("Naziv", "Naziv artikla");
    s.Columns.Add("Dobavljac.Naziv", "Dobavljač");
    s.SettingsPager.PageSize = 8;
    s.Width = Unit.Percentage(100);
    s.KeyFieldName = "Id";
    s.Settings.ShowFilterRow = true;
    s.ClientSideEvents.BeginCallback = "gvPretragaArtikalaBeginCallback";
}).Bind(Model).GetHtml()
      